version: '3'
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: playwdocker
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  app:
    image: andhikarama/play-w-docker:v.1
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/playwdocker?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123
      SERVER_PORT: 8080
    ports:
      - "8081:8080"